author: eccentric_nz
description: AutoColour is a chat plugin for automatically changing the colour of
  keywords typed into chat.
main: me.eccentric_nz.plugins.autocolour.AutoColour
name: AutoColour
startup: postworld
dev-url: http://dev.bukkit.org/server-mods/autocolour/
version: '1.0.3'
softdepend : [Herochat]
permissions:
  autocolour.admin:
    description: Allow players access administer AutoColour.
    default: op
  autocolour.use:
    description: Show players chat with AutoColour.
    default: true
commands:
  autocolour:
    aliases: [ac, autocolor]
    description: Add an AutoColour word.
    usage: /<command> [word] [colour]
    permission: autocolour.admin
    permission-message: You don't have the permission <permission> to use this command
  acremove:
    aliases: [acr, autocolourremove, autocolorremove]
    description: Remove an AutoColour word.
    usage: /<command> [word]
    permission: autocolour.admin
    permission-message: You don't have the permission <permission> to use this command
  aclist:
    aliases: [acl, autocolourlist, autocolorlist]
    description: Lists all AutoColour words.
    usage: /<command>
    permission: autocolour.use
    permission-message: You don't have the permission <permission> to use this command